// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARO1yJyITuObfCVAjTQwm0tmvcVln99jA',
    appId: '1:1071814598110:web:c4673d76352e94289e914f',
    messagingSenderId: '1071814598110',
    projectId: 'miji-fire-flutter',
    authDomain: 'miji-fire-flutter.firebaseapp.com',
    storageBucket: 'miji-fire-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ioUP8VUyT5GApZxtiOO12Izx7kGTOKY',
    appId: '1:1071814598110:android:1d6a875b7547e6529e914f',
    messagingSenderId: '1071814598110',
    projectId: 'miji-fire-flutter',
    storageBucket: 'miji-fire-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr3QVT52gxhYCMJxN4mnUP4KXjk8DGNq8',
    appId: '1:1071814598110:ios:af6d2489a8c7a91f9e914f',
    messagingSenderId: '1071814598110',
    projectId: 'miji-fire-flutter',
    storageBucket: 'miji-fire-flutter.appspot.com',
    iosClientId: '1071814598110-m6pe7foor2fjnmcq1bpamm55tv51impo.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenLight',
  );
}
